### ISSUE TITLE
Issues With ALphone

### ISSUE THREAD

**Issue by MisterMike99** [ESX-PUBLIC/esx_ALphone-Blackberry-system#1]
1 - When i try to send a SMS to someone, i cant write (the mouse dont show up) i press enter and send a blank SMS.

2 - When i close the phone the animation dont stop/close/cancelled

**Comment by DarkZiko** [comment]
You must click Esc to remove this animation but for the mouse I have the same problem.

**Comment by FonWasH** [comment]
Same here, the mouse doesn't work, so the phone is not useable.
Pareille pour moi, la souris ne s'affiche pas, du coup le téléphone est inutilisable.

**Comment by ereshkigalfr** [comment]
There's no problem with the phone. Just read the code.

**Comment by clumsyzombie** [comment]
Ok i understand the read me. But let me put the steps i have done out some one tell me where i have gone wrong please.

Went into the resources and [esx] took out the old esx_phone and placed in esx_ALphone and esx_blackberry.
Renamed esx_ALphone to esx_phone3.
Went into server.cfg and took out esx_phone and placed in start esx_phone3 and start esx_blackberry
I then go in the dB and add blackberry under items like
blackberry blackberry
Then I start the server it starts and places blackberry under user_iteams with 0 under amount. Login then see nothing when I push up on arrows all I get is player list.

**Comment by MrLutin** [comment]
No support for this ressources !!! If you dont read the code dont ask a question all of response is in the code !!!
